"""Generate folder-per-concept skeletons + aggregate views from manifest.json.

After v1.7, every concept lives in concepts/<NN>-<slug>/ with four artifacts:
  README.md       (skeleton header auto-managed below this script; hand-written
                   body below the MARKER line is preserved)
  lesson.tex      (never overwritten if present; subagent fleet writes this)
  code.py         (never overwritten if present; subagent fleet writes this)
  notebook.ipynb  (never overwritten if present; subagent fleet writes this)

This script re-emits:
  - README.md headers (preserves hand-content below MARKER)
  - The top-level README.md (clickable mermaid DAG)
  - html/data.json (graph data with folder URLs)
  - notebook/foundations.ipynb (aggregate index pointing at per-concept notebooks)
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
MANIFEST = json.loads((ROOT / "manifest.json").read_text())
CONCEPTS = MANIFEST["concepts"]
LEVELS = MANIFEST["levels"]

MARKER = "<!-- ⬇️  Below this line: hand-written content. Above: auto-generated by generate.py — do not edit. -->"


def folder_for(node) -> Path:
    return ROOT / "concepts" / f"{node['id']}-{node['slug']}"


def slug_of(node) -> str:
    return f"{node['id']}-{node['slug']}"


def concept_header(node) -> str:
    """Auto-managed header for the README.md."""
    prereq_links = ", ".join(
        f"[{p}](../{p}/README.md)" for p in node["prereqs"]
    ) or "_(none — entry point)_"
    used_by = [slug_of(c) for c in CONCEPTS if slug_of(node) in c["prereqs"]]
    used_links = ", ".join(
        f"[{u}](../{u}/README.md)" for u in used_by
    ) or "_(leaf node so far)_"
    return f"""# {node['title']}

**Level:** `{node['level']}`
**Concept ID:** `{slug_of(node)}`
**Prerequisites:** {prereq_links}
**Used by:** {used_links}

## Plain-English intro
{node['summary']}

## Formal definition
$$
\\text{{See hand-written content below.}}
$$

## Why this matters
_(See below.)_

## Code
The aligned runnable demo lives at [`code.py`](./code.py). CPU-runnable, <30 s.

## Lesson PDF
See [`lesson.pdf`](./lesson.pdf) once CI has rendered it; source is [`lesson.tex`](./lesson.tex).

## Interactive notebook
See [`notebook.ipynb`](./notebook.ipynb) — open in Colab/Jupyter for cell-by-cell execution.

## Try it yourself
_(See below.)_

## Further reading
_(See below.)_

{MARKER}

<!-- Add hand-written content below: full plain-English exposition, formal
     definition body, worked examples, theorems, why-it-matters paragraph
     tying to specific papers, exercises, references. -->
"""


def write_preserving_marker(path: Path, new_header: str):
    """Seed a new README from the stock header ONLY when missing.

    After v1.8, the above-MARKER zone in each README carries an
    auto-injected '📖 Symbols you'll see in this lesson' section.
    The previous "rewrite the header on every regen" logic destroyed
    that zone, breaking the CI Generator-Idempotency check (which in
    turn blocked render-pdfs / commit-pdfs for 3 commits).

    Per-concept READMEs are now treated as user-owned content. Manifest
    changes (e.g. new prereqs) are not auto-propagated by this script;
    if needed, run a dedicated re-seed utility outside the
    idempotency-checked path.
    """
    if not path.exists():
        path.write_text(new_header)
    # else: existing content (skeleton or substantive) is preserved as-is.


def _LEVELS_TABLE_NOTE_DROPPED_COLOR_COLUMN_ABOVE():
    """The Pick-your-entry-point table now has 3 columns (Order, Level, Audience).
    The level color stays in the legend on the SVG; no need in the table."""

def concept_index() -> str:
    """Plain markdown index — clickable on GitHub browse view, no JS needed."""
    by_level = {}
    for c in CONCEPTS:
        by_level.setdefault(c["level"], []).append(c)
    lines = []
    for level_name in sorted(LEVELS.keys(), key=lambda n: LEVELS[n]["order"]):
        if level_name not in by_level:
            continue
        lines.append(f"\n### {LEVELS[level_name]['label']}\n")
        for c in by_level[level_name]:
            sl = slug_of(c)
            lines.append(
                f"- **{c['id']}** [{c['title']}](concepts/{sl}/README.md) — {c['summary']}"
            )
    return "\n".join(lines)


def top_readme() -> str:
    levels_table = "\n".join(
        f"| {info['order']} | `{name}` | {info['label']} |"
        for name, info in sorted(LEVELS.items(), key=lambda x: x[1]['order'])
    )
    tours_table = """
| Tour | Audience | File |
|------|----------|------|
| Novice | "I don't know what a function is" | [`tours/novice.md`](tours/novice.md) |
| CS undergrad | "I know calc, want probability" | [`tours/cs-undergrad.md`](tours/cs-undergrad.md) |
| Math grad | "I know measure theory" | [`tours/math-grad.md`](tours/math-grad.md) |
| Researcher | "Skip to a paper's foundations" | [`tours/researcher.md`](tours/researcher.md) |
"""
    return f"""# math-foundations

> A canonical mathematical foundations graph — {len(CONCEPTS)} concepts spanning sets through optimal transport — used as the shared substrate for the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) Claude Code skill's per-study learning maps.

## 🌐 Interactive views

| View | URL | Best for |
|------|-----|----------|
| 🔵 **D3 force graph** — drag, zoom, filter | [`pleyva2004.github.io/math-foundations/html/`](https://pleyva2004.github.io/math-foundations/html/) | Exploring relationships visually |
| 🗺️ **Clickable SVG dependency graph** | [`pleyva2004.github.io/math-foundations/html/graph.svg`](https://pleyva2004.github.io/math-foundations/html/graph.svg) | Click any node → jump to that concept |
| 📓 **Aggregate Jupyter notebook** | [`notebook/foundations.ipynb`](notebook/foundations.ipynb) | Cell-by-cell linked index |

> **Note:** the live URLs above are served by GitHub Pages. If they don't work, enable Pages: *Settings → Pages → Source: Deploy from a branch → main → /(root) → Save*.

## The dependency graph

[![math-foundations dependency graph](html/graph.svg)](https://pleyva2004.github.io/math-foundations/html/graph.svg)

*Click the image above → opens the live SVG where each node is a working link to its concept folder.*

## 📖 Notation glossary

Every distinct mathematical symbol used across the {len(CONCEPTS)} concept lessons is indexed in a single auto-generated glossary — the canonical "what does this symbol mean and where does it first appear?" lookup:

- 📑 **Markdown (browse on GitHub):** [`NOTATION.md`](NOTATION.md)
- 📄 **PDF cheatsheet (CI-compiled):** [`notation.pdf`](notation.pdf) — source: [`notation.tex`](notation.tex)
- 🧩 **Single source of truth (machine-readable):** [`notation.json`](notation.json)

Regenerate after editing `notation.json`:

```bash
python generate_notation.py
```

## Each concept ships four artifacts

Every concept lives in `concepts/<NN>-<slug>/`:
1. `README.md` — plain-English intro + LaTeX math + cross-links.
2. `lesson.tex` → `lesson.pdf` (CI-rendered) — standalone formal exposition with theorem + proof.
3. `code.py` — runnable demonstration (<30 s on CPU; finite/discrete witness for abstract concepts).
4. `notebook.ipynb` — interactive Jupyter form, runnable in Colab.

## Pick your entry point

| Order | Level | Audience |
|-------|-------|----------|
{levels_table}

### Curated tours
{tours_table}

## Concept index (clickable)

The full {len(CONCEPTS)}-concept list, by level. Every entry below is a working markdown link.
{concept_index()}

## How the graph evolves

When the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) skill encounters a paper whose math deep dive defines a concept not yet in this graph, Stage 7 of the skill adds it here. This repo is the durable shared substrate.

## Regenerating views from `manifest.json`

```bash
python generate.py            # refresh README, html/data.json, aggregate notebook
python generate_svg.py        # refresh html/graph.svg
python generate_notation.py   # refresh NOTATION.md and notation.tex from notation.json
python validate_bodies.py     # quality-gate the 42 concept folders
```

## License

MIT.
"""


def html_data() -> str:
    nodes = [
        {
            "id": c["id"],
            "slug": c["slug"],
            "title": c["title"],
            "level": c["level"],
            "summary": c["summary"],
            "color": LEVELS[c["level"]]["color"],
            "url": f"concepts/{slug_of(c)}/README.md",
        }
        for c in CONCEPTS
    ]
    links = []
    for c in CONCEPTS:
        for prereq in c["prereqs"]:
            links.append({"source": prereq.split("-")[0], "target": c["id"]})
    return json.dumps({"nodes": nodes, "links": links}, indent=2)


def aggregate_notebook() -> str:
    """Aggregator notebook that LINKS OUT to each per-concept notebook
    rather than duplicating their content."""
    cells = [{
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Math Foundations — Aggregate Index\n",
            "\n",
            "This notebook is an index. Each concept has its own runnable notebook at\n",
            "`concepts/<NN>-<slug>/notebook.ipynb` — open those directly for cell-by-cell execution.\n",
        ],
    }]
    by_level = {}
    for c in CONCEPTS:
        by_level.setdefault(c["level"], []).append(c)
    for level_name in sorted(LEVELS.keys(), key=lambda n: LEVELS[n]["order"]):
        if level_name not in by_level:
            continue
        cells.append({
            "cell_type": "markdown", "metadata": {},
            "source": [f"## Level: {LEVELS[level_name]['label']}\n"],
        })
        for c in by_level[level_name]:
            sl = slug_of(c)
            cells.append({
                "cell_type": "markdown", "metadata": {},
                "source": [
                    f"### {c['id']}: {c['title']}\n",
                    "\n",
                    f"**Prereqs:** {', '.join(c['prereqs']) or '(none)'}\n",
                    "\n",
                    f"{c['summary']}\n",
                    "\n",
                    f"📖 [README](../concepts/{sl}/README.md)  ·  ",
                    f"📓 [Notebook](../concepts/{sl}/notebook.ipynb)  ·  ",
                    f"💻 [Code](../concepts/{sl}/code.py)  ·  ",
                    f"📄 [Lesson PDF](../concepts/{sl}/lesson.pdf)\n",
                ],
            })
    return json.dumps({
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4, "nbformat_minor": 5
    }, indent=1)


def main():
    (ROOT / "concepts").mkdir(exist_ok=True)
    (ROOT / "html").mkdir(exist_ok=True)
    (ROOT / "notebook").mkdir(exist_ok=True)

    refreshed = 0
    for c in CONCEPTS:
        folder = folder_for(c)
        folder.mkdir(exist_ok=True)
        readme = folder / "README.md"
        write_preserving_marker(readme, concept_header(c))
        refreshed += 1
        # lesson.tex / code.py / notebook.ipynb: never overwrite. Subagent owns those.

    (ROOT / "README.md").write_text(top_readme())
    (ROOT / "html" / "data.json").write_text(html_data())
    (ROOT / "notebook" / "foundations.ipynb").write_text(aggregate_notebook())

    print(f"Refreshed {refreshed} concept READMEs (hand-content preserved).")
    print(f"Refreshed top-level README, html/data.json, notebook/foundations.ipynb.")


if __name__ == "__main__":
    main()
