"""Generate concept .md, code .py, README.md, html/data.json, and notebook
from manifest.json.

Idempotent: re-running overwrites generated files but never deletes hand-edited
ones. Concept files use a "do not edit above this line" marker so a subsequent
generator run can replace the auto-generated header without losing manual content.
"""

import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).parent
MANIFEST = json.loads((ROOT / "manifest.json").read_text())
CONCEPTS = MANIFEST["concepts"]
LEVELS = MANIFEST["levels"]

MARKER = "<!-- ⬇️  Below this line: hand-written content. Above: auto-generated by generate.py — do not edit. -->"


def concept_md(node) -> str:
    """Generate the auto-managed header of a concept .md file."""
    prereq_links = ", ".join(f"[[{p}]](../concepts/{p}.md)" for p in node["prereqs"]) or "_(none — entry point)_"
    used_by = [c["id"] + "-" + c["slug"] for c in CONCEPTS if (node["id"] + "-" + node["slug"]) in c["prereqs"]]
    used_links = ", ".join(f"[[{u}]](../concepts/{u}.md)" for u in used_by) or "_(leaf node so far)_"
    return f"""# {node['title']}

**Level:** `{node['level']}`
**Concept ID:** `{node['id']}-{node['slug']}`
**Prerequisites:** {prereq_links}
**Used by:** {used_links}

## Plain-English intro
{node['summary']}

## Formal definition
$$
\\text{{See hand-written content below.}}
$$

## Why this matters
_(See below — connects to specific paper/improvement concepts.)_

## Code
The aligned code lives at [`../code/{node['id']}-{node['slug']}.py`](../code/{node['id']}-{node['slug']}.py).
It demonstrates the concept on a discrete or finite example, runnable in <30 s on CPU.

## Try it yourself
_(See below.)_

## Further reading
_(See below.)_

{MARKER}

<!-- Add hand-written content below: full plain-English exposition,
     formal LaTeX definition, why-it-matters paragraph tying to specific
     papers, code description with expected output, exercises, references. -->
"""


def concept_py(node) -> str:
    """Generate a runnable skeleton .py for a concept."""
    return f'''"""{node['title']} — concept {node['id']}-{node['slug']} of the math-foundations learning map.

{node['summary']}

This is the auto-generated skeleton. Replace the body of main() with a
concrete, CPU-runnable demonstration of the concept (≤30 s, ≤80 lines).
For abstract concepts, implement a finite/discrete witness.
"""


def main():
    print("{node['title']} (concept {node['id']}-{node['slug']})")
    print("=" * 60)
    print("TODO: implement a runnable demonstration of this concept.")
    print()
    print("See ../concepts/{node['id']}-{node['slug']}.md for the formal definition.")


if __name__ == "__main__":
    main()
'''


def mermaid_graph() -> str:
    """Generate the full mermaid DAG covering all concepts + edges."""
    lines = ["```mermaid", "graph TD"]
    # Style classes per level
    for level_name, info in LEVELS.items():
        lines.append(f"  classDef {level_name} fill:{info['color']},stroke:#333,stroke-width:1px;")
    # Nodes
    for c in CONCEPTS:
        node_id = c["id"]
        title = c["title"].replace('"', "'")
        lines.append(f'  {node_id}["{node_id}: {title}"]')
    # Edges
    for c in CONCEPTS:
        for prereq in c["prereqs"]:
            prereq_id = prereq.split("-")[0]
            lines.append(f"  {prereq_id} --> {c['id']}")
    # Level classes
    for c in CONCEPTS:
        lines.append(f"  class {c['id']} {c['level']};")
    # Click directives
    for c in CONCEPTS:
        lines.append(f'  click {c["id"]} "concepts/{c["id"]}-{c["slug"]}.md" "{c["title"]}"')
    lines.append("```")
    return "\n".join(lines)


def readme() -> str:
    levels_table = "\n".join(
        f"| {info['order']} | `{name}` | {info['label']} | Color {info['color']} |"
        for name, info in sorted(LEVELS.items(), key=lambda x: x[1]['order'])
    )
    tours_table = """
| Tour | Audience | File |
|------|----------|------|
| Novice | "I don't know what a function is" | [`tours/novice.md`](tours/novice.md) |
| CS undergrad | "I know calc, want probability" | [`tours/cs-undergrad.md`](tours/cs-undergrad.md) |
| Math grad | "I know measure theory" | [`tours/math-grad.md`](tours/math-grad.md) |
| Researcher | "Skip to a paper's foundations" | [`tours/researcher.md`](tours/researcher.md) |
"""
    return f"""# math-foundations

> A canonical mathematical foundations graph used as the shared substrate for the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) Claude Code skill's per-study learning maps.

Every concept here has three aligned representations:
1. A Markdown concept page (`concepts/<NN>-<slug>.md`) with plain-English intro, formal LaTeX definition, and exercises.
2. A runnable Python demonstration (`code/<NN>-<slug>.py`) — CPU, <30 s, finite/discrete witness for abstract concepts.
3. A node in the graph below, clickable from GitHub's browse view, navigable in three formats: mermaid (this README), Jupyter ([`notebook/foundations.ipynb`](notebook/foundations.ipynb)), and HTML force graph ([`html/index.html`](html/index.html)).

## Pick your entry point

| Order | Level | Audience | Style |
|-------|-------|----------|-------|
{levels_table}

### Curated tours
{tours_table}

## The graph

{mermaid_graph()}

## Status

This is **v0.1** — the framework is complete, manifest covers {len(CONCEPTS)} concepts, every concept has a skeleton concept page and runnable .py shell. Hand-written content lives below the `do not edit` marker in each concept file. Filling in detail proceeds level-by-level.

## How the graph evolves

When the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) skill encounters a paper whose math deep dive defines a concept not yet in this graph, Stage 7 of the skill proposes adding it to this repo as a new node. The skill is the primary growth driver; this repo is the durable shared substrate.

## License

MIT.
"""


def html_data() -> str:
    nodes = [
        {
            "id": c["id"],
            "slug": c["slug"],
            "title": c["title"],
            "level": c["level"],
            "summary": c["summary"],
            "color": LEVELS[c["level"]]["color"],
        }
        for c in CONCEPTS
    ]
    links = []
    for c in CONCEPTS:
        for prereq in c["prereqs"]:
            links.append({"source": prereq.split("-")[0], "target": c["id"]})
    return json.dumps({"nodes": nodes, "links": links}, indent=2)


def notebook() -> str:
    """Generate a minimal valid Jupyter notebook with one markdown+code cell pair per concept."""
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Math Foundations — Interactive Notebook\n",
                "\n",
                "Progressive cells across all foundation concepts.\n",
                "Open in Colab or Jupyter Lab; run cells top-to-bottom or jump to a section.\n",
            ],
        }
    ]
    by_level = {}
    for c in CONCEPTS:
        by_level.setdefault(c["level"], []).append(c)
    for level_name in sorted(LEVELS.keys(), key=lambda n: LEVELS[n]["order"]):
        if level_name not in by_level:
            continue
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [f"## Level: {LEVELS[level_name]['label']}\n"],
        })
        for c in by_level[level_name]:
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"### {c['id']}: {c['title']}\n",
                    "\n",
                    f"**Prereqs:** {', '.join(c['prereqs']) or '(none)'}\n",
                    "\n",
                    f"{c['summary']}\n",
                    "\n",
                    f"See `concepts/{c['id']}-{c['slug']}.md` for the full concept page.\n",
                ],
            })
            # Embed the code as a cell so the reader can execute it.
            code_path = ROOT / "code" / f"{c['id']}-{c['slug']}.py"
            if code_path.exists():
                src = code_path.read_text().splitlines(keepends=True)
            else:
                src = ["# (code not yet generated)\n"]
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": src,
            })
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(nb, indent=1)


def write_if_managed_safe(path: Path, new_content: str):
    """Write `new_content` to `path`. If the file exists and contains the
    MARKER, preserve everything below the marker (hand-written content).
    """
    if path.exists() and MARKER in path.read_text():
        existing = path.read_text()
        below = existing.split(MARKER, 1)[1]
        path.write_text(new_content.split(MARKER, 1)[0] + MARKER + below)
    else:
        path.write_text(new_content)


def main():
    (ROOT / "concepts").mkdir(exist_ok=True)
    (ROOT / "code").mkdir(exist_ok=True)
    (ROOT / "html").mkdir(exist_ok=True)
    (ROOT / "notebook").mkdir(exist_ok=True)

    written = 0
    for c in CONCEPTS:
        md_path = ROOT / "concepts" / f"{c['id']}-{c['slug']}.md"
        py_path = ROOT / "code" / f"{c['id']}-{c['slug']}.py"
        write_if_managed_safe(md_path, concept_md(c))
        # .py files: only write if missing (preserve hand-edits entirely).
        if not py_path.exists():
            py_path.write_text(concept_py(c))
            written += 1
        else:
            # Don't clobber hand-written code.
            pass

    (ROOT / "README.md").write_text(readme())
    (ROOT / "html" / "data.json").write_text(html_data())
    (ROOT / "notebook" / "foundations.ipynb").write_text(notebook())

    print(f"Generated:")
    print(f"  concepts/: {len(CONCEPTS)} .md files (header refreshed; hand-content preserved)")
    print(f"  code/:     {written} new .py files (existing preserved)")
    print(f"  README.md, html/data.json, notebook/foundations.ipynb")


if __name__ == "__main__":
    main()
