"""Generate folder-per-concept skeletons + aggregate views from manifest.json.

After v1.7, every concept lives in concepts/<NN>-<slug>/ with four artifacts:
  README.md       (skeleton header auto-managed below this script; hand-written
                   body below the MARKER line is preserved)
  lesson.tex      (never overwritten if present; subagent fleet writes this)
  code.py         (never overwritten if present; subagent fleet writes this)
  notebook.ipynb  (never overwritten if present; subagent fleet writes this)

This script re-emits:
  - README.md headers (preserves hand-content below MARKER)
  - The top-level README.md (clickable mermaid DAG)
  - html/data.json (graph data with folder URLs)
  - notebook/foundations.ipynb (aggregate index pointing at per-concept notebooks)
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
MANIFEST = json.loads((ROOT / "manifest.json").read_text())
CONCEPTS = MANIFEST["concepts"]
LEVELS = MANIFEST["levels"]

MARKER = "<!-- ⬇️  Below this line: hand-written content. Above: auto-generated by generate.py — do not edit. -->"


def folder_for(node) -> Path:
    return ROOT / "concepts" / f"{node['id']}-{node['slug']}"


def slug_of(node) -> str:
    return f"{node['id']}-{node['slug']}"


def concept_header(node) -> str:
    """Auto-managed header for the README.md."""
    prereq_links = ", ".join(
        f"[{p}](../{p}/README.md)" for p in node["prereqs"]
    ) or "_(none — entry point)_"
    used_by = [slug_of(c) for c in CONCEPTS if slug_of(node) in c["prereqs"]]
    used_links = ", ".join(
        f"[{u}](../{u}/README.md)" for u in used_by
    ) or "_(leaf node so far)_"
    return f"""# {node['title']}

**Level:** `{node['level']}`
**Concept ID:** `{slug_of(node)}`
**Prerequisites:** {prereq_links}
**Used by:** {used_links}

## Plain-English intro
{node['summary']}

## Formal definition
$$
\\text{{See hand-written content below.}}
$$

## Why this matters
_(See below.)_

## Code
The aligned runnable demo lives at [`code.py`](./code.py). CPU-runnable, <30 s.

## Lesson PDF
See [`lesson.pdf`](./lesson.pdf) once CI has rendered it; source is [`lesson.tex`](./lesson.tex).

## Interactive notebook
See [`notebook.ipynb`](./notebook.ipynb) — open in Colab/Jupyter for cell-by-cell execution.

## Try it yourself
_(See below.)_

## Further reading
_(See below.)_

{MARKER}

<!-- Add hand-written content below: full plain-English exposition, formal
     definition body, worked examples, theorems, why-it-matters paragraph
     tying to specific papers, exercises, references. -->
"""


def write_preserving_marker(path: Path, new_header: str):
    """Write the header portion; preserve any existing content below MARKER.

    SAFETY: If the file exists and is non-trivial (>200 chars) but lacks the
    MARKER, do NOT overwrite — the user/subagent has authored substantive
    content without the marker contract. Re-running this script must never
    destroy hand-written work.
    """
    if not path.exists():
        path.write_text(new_header)
        return
    existing = path.read_text()
    if MARKER in existing:
        below = existing.split(MARKER, 1)[1]
        path.write_text(new_header.split(MARKER, 1)[0] + MARKER + below)
    elif len(existing) <= 200:
        # Empty / placeholder; safe to seed.
        path.write_text(new_header)
    # else: substantive content without marker — leave it alone.


def mermaid_graph() -> str:
    lines = ["```mermaid", "graph TD"]
    for level_name, info in LEVELS.items():
        lines.append(f"  classDef {level_name} fill:{info['color']},stroke:#333,stroke-width:1px;")
    for c in CONCEPTS:
        node_id = c["id"]
        title = c["title"].replace('"', "'")
        lines.append(f'  {node_id}["{node_id}: {title}"]')
    for c in CONCEPTS:
        for prereq in c["prereqs"]:
            prereq_id = prereq.split("-")[0]
            lines.append(f"  {prereq_id} --> {c['id']}")
    for c in CONCEPTS:
        lines.append(f"  class {c['id']} {c['level']};")
    for c in CONCEPTS:
        # Click navigates to the folder's README.
        lines.append(f'  click {c["id"]} "concepts/{slug_of(c)}/README.md" "{c["title"]}"')
    lines.append("```")
    return "\n".join(lines)


def top_readme() -> str:
    levels_table = "\n".join(
        f"| {info['order']} | `{name}` | {info['label']} | Color {info['color']} |"
        for name, info in sorted(LEVELS.items(), key=lambda x: x[1]['order'])
    )
    tours_table = """
| Tour | Audience | File |
|------|----------|------|
| Novice | "I don't know what a function is" | [`tours/novice.md`](tours/novice.md) |
| CS undergrad | "I know calc, want probability" | [`tours/cs-undergrad.md`](tours/cs-undergrad.md) |
| Math grad | "I know measure theory" | [`tours/math-grad.md`](tours/math-grad.md) |
| Researcher | "Skip to a paper's foundations" | [`tours/researcher.md`](tours/researcher.md) |
"""
    return f"""# math-foundations

> A canonical mathematical foundations graph used as the shared substrate for the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) Claude Code skill's per-study learning maps.

Each concept lives in `concepts/<NN>-<slug>/` and ships **four artifacts**:
1. `README.md` — plain-English intro + LaTeX math + cross-links (GitHub-renderable).
2. `lesson.tex` — standalone-compilable formal LaTeX exposition; CI renders to `lesson.pdf`.
3. `code.py` — runnable demonstration (<30 s on CPU; finite/discrete witness for abstract concepts).
4. `notebook.ipynb` — interactive Jupyter form, runnable cell-by-cell in Colab.

Plus three interactive aggregate views: mermaid (this README), notebook ([`notebook/foundations.ipynb`](notebook/foundations.ipynb), an index), and HTML force graph ([`html/index.html`](html/index.html)).

## Pick your entry point

| Order | Level | Audience | Style |
|-------|-------|----------|-------|
{levels_table}

### Curated tours
{tours_table}

## The graph

{mermaid_graph()}

## Status

This is **v0.1** of the framework with v1.7 folder layout. All {len(CONCEPTS)} concepts have folders + skeleton headers. The subagent fleet (v1.7 Part 2) fills the bodies.

## How the graph evolves

When the [`study-paper`](https://github.com/pleyva2004/claude-skill-study-paper) skill encounters a paper whose math deep dive defines a concept not yet in this graph, Stage 7 of the skill adds it here. This repo is the durable shared substrate.

## License

MIT.
"""


def html_data() -> str:
    nodes = [
        {
            "id": c["id"],
            "slug": c["slug"],
            "title": c["title"],
            "level": c["level"],
            "summary": c["summary"],
            "color": LEVELS[c["level"]]["color"],
            "url": f"concepts/{slug_of(c)}/README.md",
        }
        for c in CONCEPTS
    ]
    links = []
    for c in CONCEPTS:
        for prereq in c["prereqs"]:
            links.append({"source": prereq.split("-")[0], "target": c["id"]})
    return json.dumps({"nodes": nodes, "links": links}, indent=2)


def aggregate_notebook() -> str:
    """Aggregator notebook that LINKS OUT to each per-concept notebook
    rather than duplicating their content."""
    cells = [{
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Math Foundations — Aggregate Index\n",
            "\n",
            "This notebook is an index. Each concept has its own runnable notebook at\n",
            "`concepts/<NN>-<slug>/notebook.ipynb` — open those directly for cell-by-cell execution.\n",
        ],
    }]
    by_level = {}
    for c in CONCEPTS:
        by_level.setdefault(c["level"], []).append(c)
    for level_name in sorted(LEVELS.keys(), key=lambda n: LEVELS[n]["order"]):
        if level_name not in by_level:
            continue
        cells.append({
            "cell_type": "markdown", "metadata": {},
            "source": [f"## Level: {LEVELS[level_name]['label']}\n"],
        })
        for c in by_level[level_name]:
            sl = slug_of(c)
            cells.append({
                "cell_type": "markdown", "metadata": {},
                "source": [
                    f"### {c['id']}: {c['title']}\n",
                    "\n",
                    f"**Prereqs:** {', '.join(c['prereqs']) or '(none)'}\n",
                    "\n",
                    f"{c['summary']}\n",
                    "\n",
                    f"📖 [README](../concepts/{sl}/README.md)  ·  ",
                    f"📓 [Notebook](../concepts/{sl}/notebook.ipynb)  ·  ",
                    f"💻 [Code](../concepts/{sl}/code.py)  ·  ",
                    f"📄 [Lesson PDF](../concepts/{sl}/lesson.pdf)\n",
                ],
            })
    return json.dumps({
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4, "nbformat_minor": 5
    }, indent=1)


def main():
    (ROOT / "concepts").mkdir(exist_ok=True)
    (ROOT / "html").mkdir(exist_ok=True)
    (ROOT / "notebook").mkdir(exist_ok=True)

    refreshed = 0
    for c in CONCEPTS:
        folder = folder_for(c)
        folder.mkdir(exist_ok=True)
        readme = folder / "README.md"
        write_preserving_marker(readme, concept_header(c))
        refreshed += 1
        # lesson.tex / code.py / notebook.ipynb: never overwrite. Subagent owns those.

    (ROOT / "README.md").write_text(top_readme())
    (ROOT / "html" / "data.json").write_text(html_data())
    (ROOT / "notebook" / "foundations.ipynb").write_text(aggregate_notebook())

    print(f"Refreshed {refreshed} concept READMEs (hand-content preserved).")
    print(f"Refreshed top-level README, html/data.json, notebook/foundations.ipynb.")


if __name__ == "__main__":
    main()
